spring.application.name=thymleaf_crud2
spring.datasource.url=jdbc:mysql://10.0.140.117:3306/student?createDatabaseIfNotExists=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
server.port=8086

